name: viso_studio_flutter
description: A new Flutter version of Viso Studio Community.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Network
  http: ^1.1.0
  
  # Icons
  phosphor_flutter: ^2.0.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Animations
  flutter_animate: ^4.2.0

  # SVG Support
  flutter_svg: ^2.0.10+1
  
  # Fonts
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
